/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RscServerComponentRouteImport } from './routes/rsc/ServerComponent'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RscServerComponentRoute = RscServerComponentRouteImport.update({
  id: '/rsc/ServerComponent',
  path: '/rsc/ServerComponent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/rsc/ServerComponent': typeof RscServerComponentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/rsc/ServerComponent': typeof RscServerComponentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/rsc/ServerComponent': typeof RscServerComponentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/rsc/ServerComponent'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/rsc/ServerComponent'
  id: '__root__' | '/' | '/rsc/ServerComponent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RscServerComponentRoute: typeof RscServerComponentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsc/ServerComponent': {
      id: '/rsc/ServerComponent'
      path: '/rsc/ServerComponent'
      fullPath: '/rsc/ServerComponent'
      preLoaderRoute: typeof RscServerComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RscServerComponentRoute: RscServerComponentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
